/* FontAwesome Icons */
import { library } from '@fortawesome/fontawesome-svg-core'

import { 
  faInfoCircle,
  faExclamationTriangle,
  faExclamationCircle,
  faCheck,
  faPowerOff,
  faUserCircle,
  faHome,
  faCircleNotch,
  faPhoneSquareAlt,
  faInbox,
  faCalendarAlt,
  faCalendarDay,
  faUserCheck,
  faRoute,
  faBuilding,
  faRoad,
  faMapMarkerAlt,
  faEye,
  faEyeSlash,
  faPhoneAlt,
  faClipboard,
  faClipboardList,
  faClipboardCheck,
  faToolbox,
  faStoreAlt,
  faTools,
  faSyncAlt,
  faPauseCircle,
  faCog,
  faRetweet,
  faRedoAlt,
  faFingerprint,
  faQuestionCircle,
  faUserLock,
  faAngleLeft,
  faKey,
  faVoteYea,
} from '@fortawesome/free-solid-svg-icons'



import { 
  faCheckCircle as farCheckCircle,
} from '@fortawesome/free-regular-svg-icons'



library.add(
  faInfoCircle,
  faExclamationTriangle,
  faExclamationCircle,
  farCheckCircle,
  faCheck,
  faPowerOff,
  faUserCircle,
  faHome,
  faCircleNotch,
  faPhoneSquareAlt,
  faInbox,
  faCalendarAlt,
  faCalendarDay,
  faUserCheck,
  faRoute,
  faBuilding,
  faRoad,
  faMapMarkerAlt,
  faEye,
  faEyeSlash,
  faPhoneAlt,
  faClipboard,
  faClipboardList,
  faClipboardCheck,
  faToolbox,
  faStoreAlt,
  faInfoCircle,
  faTools,
  faSyncAlt,
  faPauseCircle,
  faCog,
  faRetweet,
  faRedoAlt,
  faFingerprint,
  faQuestionCircle,
  faUserLock,
  faAngleLeft,
  faKey,
  faVoteYea,
)